const DECKS = {
  "Dating": [
    {title:"Küsimus",desc:"Mis on su lemmik kohtingu mälestus?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Millist nõu annaksid oma 18-aastasele minale?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis tegevus teeb sind suhtes kõige õnnelikumaks?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas eelistad kinke? Kallistusi? Komplimente?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mida sa minus esimesena märkasid?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kus on ideaalne kohtinguõhtu sinu jaoks?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis harjumus mul on, mis sulle meeldib?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis paneb sind suhtes turvaliselt tundma?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis on asi, mida sa teed ainult siis kui oled üksi?", foot:"• kohtingu küsimused" },
    {title:"Küsimus",desc:"Mida sa tahad elus veel ära õppida?", foot:"• kohtingu küsimused" },
    {title:"Küsimus",desc:"Mis on kõige hullem kohtingulugu/kogemus, mida sa tead?", foot:"• kohtingu küsimused" },
    {title:"Küsimus",desc:"Kui su elu oleks film, mida publik karjuks, et sa praegu tegema peaksid?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis on su unistuste reis kahekesi?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis on su lemmik date koostegevus?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Millal sa tundsid, et klapp on olemas?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis kompliment sulle kõige rohkem meeldib?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kohv või tee?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas oled rohkem hommiku- või õhtuinimene?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas eelistad uhket ja kallist või odavat ja lihtsat kohtingut",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mida sa ootad parimalt suhtelt?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas eelistad spontaansust või planeerimist?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis on su lemmik viis kiindumust näidata?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas sa usud hingesugulastesse?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas eelistad kodus olla või väljas käia?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis on väike žest mis sind kergelt alati rõõmustab?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas oled armukade tüüp?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis on parim kompliment, mida oled saanud?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas eelistad sügavaid vestlusi või nalja?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Milline on su ideaalne nädalavahetus kahekesi?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas naudid rohkem üllatusi või rutiini ja planeeritud tegevusi?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis on su lemmik ühine mälestus?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kuidas sulle meeldib stressi maandada?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis sulle eelmistes suhetes kõige rohkem meeldis?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas sa hoiad kellegi vastu veel vimma?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis on top 2 kahetsust su elus?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Parim lapsepõlvemälestus?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis sind viimati marru ajas?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Parim ja halvim moment seeaasta?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Parim asi mis sa oma vanematelt suhetest oled õppinud?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas sul on eelnevad suhted olnud pikemad või lühikesed?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas sul on kedagi, kellega sa kahetsed, et magasid?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas sul on kuulsus, kellega sa kohe magaksid, kui võimalus tekiks?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis on asi, mida inimesed sinust alguses valesti eeldavad?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kui sa saaksid oma seksielus midagi rohkemat, mis see oleks?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Jaga midagi mis sind erutab, mida sa pole minuga veel jaganud?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kui tihti sa soovid intiimne olla?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kudas sa kirjeldaksid mind teistele inimestele?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis kehaosa sind enda juures kõige rohkem häirib?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kui sul oleks kiiresti raha vaja kuidas sa saaksid?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mida tahaksid kindlasti elus kogeda?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Milline partneri kehaosa sulle kõige rohkem meeldib?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kui miski ei hoiaks sind Eestis, siis kus sa elaksid?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis ajas sind viimati nii naerma, et peaaegu oleksid püksi pissinud?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kui sõbrad peaksid sind kolme sõnaga kirjeldama, mis need oleks?",foot:"• kohtingu küsimused"}, 
    {title:"Küsimus",desc:"Millist kodutööd sa kõige rohkem vihkad?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Nimeta kaks asja oma “anti-bucket listist” – mida sa kindlasti teha ei taha.",foot:"• kohtingu küsimused"},
    {title:"Tegevus",desc:"Sosista mulle kõrva seksikalt ühe pesuvahendi nimi.",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Milline riietus on sinu arvates eriti atraktiivne?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Kas hääle atraktiivsus on sulle tähtis?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Milline väike luksus on sinu jaoks tegelikult väga oluline?",foot:"• kohtingu küsimused"},
    {title:"Küsimus",desc:"Mis on kõige ootamatum kompliment, mida oled saanud?",foot:"• kohtingu küsimused"}, 
    {title:"Küsimus",desc:"Kumb versioon minust sulle rohkem meeldib — päriselus või chatis?",foot:"• kohtingu küsimused"}, 
    {title:"Küsimus",desc:"Mis on muster, mida sa ei taha enam oma suhetes korrata?",foot:"• kohtingu küsimused"}                        
  ],
  "Spicy": [
    {title:"Tegevus",desc:"Sosista mulle kõrva seksikalt ühe pesuvahendi nimi.",foot:"• spicy"},
    {title:"Tegevus",desc:"Kas sina oled kunagi kellegilt maasika saanud või kellelegi maasika teinud?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis on su kõige julgemalt saadetud sõnum?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis on su lemmik viis flirtida?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas sa oled pigem dominante või passivne voodis?",foot:"• spicy"},
    {title:"Küsimus",desc:"3 kohta kus sa sooviks seksida mis ei ole voodis?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis sa voodis kindlasti ei teeks?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis sa ei ole veel kellegagi voodis teinud aga tahaks?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis on su salajane turn-on?",foot:"• spicy"},
    {title:"Küsimus",desc:"Parim aeg päeval seksiks?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis on lihtne kompliment mida sa tihti kuulda tahaks?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas sa naeraksid või punastaksid kui su otsingute ajalugu nähtavaks teha?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kust sulle meeldib ,et sind puudutatakse?",foot:"• spicy"},
    {title:"Tegevus",desc:"Vaadake üksteise silma kuni üks pilgutab",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas naudid rohkem algatamist või meeldib kui teine algatab?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas sulle meeldib sosistamine?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis on su lemmik poos voodis?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas eelistad tulesid sees või hämarust?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis riietus on sinu meelest on eriti atraktiivne?",foot:"• spicy"},
    {title:"Tegevus",desc:"See kes ette loeb saab käe panna teise reiele.",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis on asi, mida sa kunagi voodis ei teeks, aga mis tundub erutav?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas sulle meeldib kiuslik flirt?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis paneb sind partneri juures sulama?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas sulle meeldib, kui partner juhib?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas tekstis flirtimine meeldib?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis teeb su enesekindlaks?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas sulle meeldib rollimäng?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kui me tahaks midagi seksuaalset teha aga seksida ei saa. Mida me teeks?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas eelistad vaikust või muusikat?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis on su lemmik koht kahekesi olla?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas naudid pikalt silmsidet?",foot:"• spicy"},
    {title:"Küsimus",desc:"Mis on su lemmik eelmäng?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas sind on kunagi kinni seotud?",foot:"• spicy"},
    {title:"Küsimus",desc:"Kas naudid aeglast lähenemist või tahaksid vahele jätta?",foot:"• spicy"}
  ],
  "Couples": [
    {title:"Küsimus",desc:"Kuidas sa tead, et mul on halb päev olnud?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Millise harjumuse, tegevuse või ütluse oled minult omandanud?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis aitab sul pärast tüli uuesti lähedust tunda?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kas igapäevane hommikust ja head ööd tundub sulle armas või pigem üleliigne?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kas sa oled kiitnud midagi oma sõbrale oma paarilisest?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis teemal sul on kõige raskem teist inimest usaldada?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mida sa viimati kartsid teha, aga tegid siiski ära?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kumb on sinu arvates halvem juht?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Millist üritust või tähtpäeva sa igal juhul tähistad?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis sa arvad teeb meie suhet tugevaks?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis on tegevus, millega sulle varem meeldis tegeleda, kuid enam mitte?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kuidas lahendame tülisid?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis on meie ühine nõrkus?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis teeb meid heaks tiimiks?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kuidas sa tahad, et sulle hoolivust näidatakse?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Milline on sinu ühise reisi unistus?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kuidas sa soovid, et me koos kvaliteetaega veedaks?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis on asi, mida sa tahaksid suhtes teadlikumalt teha?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kuidas jagame kohustusi?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis sind rahustab?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis on meie ühine hobi?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis on su väärtused?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kuidas su eks sind kirjeldaks?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kirjelda midagi, mis sind praegu sinu elus elevile ajab?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Millised kolm oskust sa valiksid, kui saaksid need kohe selgeks õppida?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kui sa saaksid näha 10 aastat tulevikku, mida sa esimesena uuriksid?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kuidas mina saan sinu eesmärkide saavutamisele kaasa aidata?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis on kaks asja sinu bucket listist?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kas sul traditsioone?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Mis on sinu mõni naljakas kiiks?",foot:"• paaridele"},
    {title:"Küsimus",desc:"Kui sul oleks miljon eurot, mille peaksid kohe ära kulutama, mida sa sellega teeksid?",foot:"• paaridele"}
  ],
  "Party": [
    {title:"Tõsta käsi",desc:"Kui oled kunagi laval esinenud.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled elus 4 päeva järjest joonud.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled alasti ujumas käinud.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled viimase 7 päeva jooksul vaadanud pornot.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled rohkem kui aasta joomata.",foot:"• peomäng"},
    {title:"Küsimus",desc:"Kes on täna kõige kõige rohkem alkoholi tarbinud.",foot:"• peomäng"},
    {title:"Küsimus",desc:"Kes on teinud spontaanse reisi?",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled kunagi tööl valetanud, et puududa.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui film on sind nutma pannud.",foot:"• peomäng"},
    {title:"Tegevus",desc:"Kõik kes seeaasta reisinud ei ole seisavad püsti nüüd järgmised kaks küsimust.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kes on saatnud eksile sõnumi öösel?",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kes on hiljaks jäänud kohtingule?",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kes on kunagi valetanud enda kohta?",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kes on kaotanud telefoni peol?",foot:"• peomäng"},
    {title:"Küsimus",desc:"Mis on kõige kallim impulss ost olnud eurodes?",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui kardad ämblikke.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled kedagi siit suudlenud.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled rahul endaga praegu.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled midagi illegaalset teinud.",foot:"• peomäng"},
    {title:"Tegevus",desc:"Hoia kõrval oleva isiku käest kinni kaks küsimust.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled kogemata valele inimesele sõnumi saatnud.",foot:"• peomäng"},
    {title:"Tegevus",desc:"Näita näpuga kes siin seltskonnas jääks zombiapokalüpsises ellu?",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui sulle meeldib ananass pitsa peal.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui sulle meeldib talv rohkem kui suvi.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled autos pahandust teinud.",foot:"• peomäng"},
    {title:"Tegevus",desc:"Vaheta riideese kõrval oleva isikuga.",foot:"• peomäng"},
    {title:"Küsimus",desc:"Näita näpuga kes on teinud peo meeldejäävaks?",foot:"• peomäng"},
    {title:"Tegevus",desc:"Tee high-five kellegiga.",foot:"• peomäng"},
    {title:"Tegevus",desc:"Näita näpuga kes siin ei jääks kunagi hiljaks.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled kedagi kinni sidunud.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled suudelnud samast soost inimest.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled trahvi saanud viimase kahe aasta jooksul.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui oled kunagi elus teinud kanepit.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui sul on neet kuskil.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui sul on tatoveering kuskil.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui sa ei kannata oma tööd.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui sinu postituse likeide kogus mõjutab su enesetunnet.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui sa omad krüptot.",foot:"• peomäng"},
    {title:"Tõsta käsi",desc:"Kui sa oled COVIDi ajal vetsupaberit hulga ostnud.",foot:"• peomäng"},
    {title:"Tegevus",desc:"Hoia kõrval inimese särgist kinni kaks küsimust.",foot:"• peomäng"}
  ]
};

const TINTS = {
  Dating:  { A:"rgba(255,77,166,.12)", B:"rgba(255,31,143,.09)" },
  Spicy:   { A:"rgba(255,160,70,.14)", B:"rgba(255,105,0,.09)" },
  Couples: { A:"rgba(110,175,255,.12)", B:"rgba(55,120,255,.08)" },
  Party:   { A:"rgba(185,120,255,.12)", B:"rgba(125,55,255,.08)" }
};

window.DECKS = DECKS;

window.TINTS = TINTS;




